version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"   # Opsional: agar bisa diakses dari host juga
    volumes:
      - /volume1/docker/mongodb:/data/db   # Ganti dengan volume yang sesuai

  backend:
    build: ./backend
    container_name: asset-backend
    restart: unless-stopped
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - JWT_SECRET=rahasia123
      - MONGODB_URI=mongodb://mongodb:27017/inventaris   # <-- pakai nama service
    depends_on:
      - mongodb